# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 236b18a267b259871bade28036d06d15783b7798b794f7d0e88c40b7f2e61c0899fd0fa1680b31e101368c9a4df53cde421aae4fbf884da6926742b47efb3886

test:
  secret_key_base: 6120bcf590c6cdca98953b9f51542b779a1f8caf16b5b6f1c4b160061be9a958066d216cb2c56a6454ec0fd9e28378e7a74ddbc70f2cab6a5ba9c8028e2b1f6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
